databases:
  host: "localhost"
  port: 3306
  database: "rainy_day"
  username: "db user name"
  password: "db pw"
  timezone: "+09:00"

secrets:
  django: "django secret"

token:
  scret: "jwt secret"
  expire_sec: 3600

pagenation:
  default_page_size: 10

audio_output:
  path: "audio_outputs/"
  #프로젝트 이름으로 된 폴더를 생성하여 음성 데이터를 저장합니다.
  make_folder: True

