# Generated by Django 4.1.2 on 2022-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_project_management", "0002_audiodata_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiodata",
            name="path",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
